# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Permalinks
paginate:           1
permalink:          pretty

# Setup
title:              Pixels May Jitter
tagline:            Computer graphics ramblings, randomly sampled.
url:                ""
baseurl:            ""

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         _sass
  style:            :compressed

images:             /assets/images/fullres

# About/contact
author:
  name:             Thibault Schueller
  url:              https://twitter.com/schuel_t
  email:            ryp.sqrt@gmail.com

