baseURL: 'https://ryp.github.io/'
languageCode: en-us
title: 'Pixels May Jitter'
theme: papermod
paginate: 5
#theme: 'hermit'
#theme: 'hello-friend-ng'

params:
    defaultTheme: auto
    disableThemeToggle: true
    #socialIcons:
    #    - name: github
    #      url: "https://github.com/Ryp"
    #    - name: twitter
    #      url: "https://twitter.com/schuel_t"
